airtable_token = "patP8qx7lbIPOm0DJ.dbe226cbd977fa134d15badd3597c6d42096b3faea1371d13a3fecdb7aa7b866"        # Ton token Airtable
base_id = "app6ztQ6oRakoPKJv"        # Ton base ID
table_name = "Termes"    # Le nom tel qu'il apparaît dans Airtable
