name: Backup la carte des kayous Umap

on:
  schedule:
    - cron: '0 0 * * *'  # Exécute tous les jours à minuit
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Configure Git
      run: |
        git config --global user.name "edouardooo"
        git config --global user.email "edouardazoulay@orange.fr"
      env:
        GITHUB_TOKEN: ${{ secrets.BACKUPSECRET }}  # Utilisation du secret BACKUPSECRET

    - name: Install dependencies
      run: |
        pip install requests  # Installe les dépendances nécessaires

    - name: Run backup script
      run: python3 backup.py
