name: Backup automatisé

on:
  schedule:
    - cron: '0 0 * * *'  # Déclenche le backup tous les jours à minuit

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run backup script
        run: python3 backup.py  # Exécute le script Python de backup

      - name: Commit and push changes
        run: |
          git config --global user.name "Edouard Azoulay"
          git config --global user.email "edouard.azoulay@example.com"
          git add backups/
          git commit -m "Backup automatique $(date +'%Y-%m-%d-%Hh%M')"
          git push https://github.com/${{ secrets.GITHUB_ACTOR }}:${{ secrets.GH_TOKEN }}@github.com/edouardooo/Identificateur-de-roche.git
